CREATE TABLE IF NOT EXISTS navigation
(
    id   INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR NOT NULL,
    url  VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS posts
(
    id   INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR NOT NULL,
    post  VARCHAR NOT NULL,
    time INTEGER NOT NULL,
    url  VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
    id   INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR NOT NULL,
    email  VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    time INTEGER NOT NULL
);